services:
  tc01:
    image: tc01
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [ "sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app:app --host 0.0.0.0 --port 8000" ]
    ports:
      - 8000:8000
      - 8080:8080
      - 5050:80
      - 5432:5432
