# Este código define los servicios que se van a correr en el contenedor de Docker, al igual que las variables de entorno que se van a utilizar en cada uno de los servicios, las redes que se van a utilizar para la comunicación entre los servicios.

services:
  tc01:
    image: tc01
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgresdb.cfse8m80m5up.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=tc01db
      - DB_USER=tc01
      - DB_PASSWORD=basesdedatos2024
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myclient
      - KEYCLOAK_CLIENT_SECRET=3f7CYjzq6aRp1cEMhvMQn1boInnDC1RE # Secret generado en Keycloak
    depends_on:
      - keycloak
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - default

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgresdb.cfse8m80m5up.us-east-2.rds.amazonaws.com:5432/tc01db
      - KC_DB_USERNAME=tc01
      - KC_DB_PASSWORD=basesdedatos2024
    ports:
      - "8080:8080"
    command:
      - start-dev
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  pgadmin_data:
